### ISSUE TITLE
Create controler and required endpoints for expence tracker

### ISSUE THREAD

**Issue by tommiAtGit** [tommiAtGit/expencetracker#1]
- [ ] As a system architect I want to have endpont for expence addition called /expence/addexpence
- [ ] As a system architect I want to have endpoint for listing all expences calld /epence/expences
- [ ] As a system architect I want to have endpoint for readeing details of single expence calld /expence/expencedetails
- [ ] As a user I want to be able to modify expance details via endpoint called /expence/updateexpence
- [ ] As a user I want to have ability to delete expence via enpoint called /expence/removeexpence
